---
- name: Power up Cisco IMC servers
  hosts: '{{ hosts_group_name }}'
  gather_facts: no

  tasks:
    - name: Power up server
      imc_rest:
        hostname: '{{ inventory_hostname }}'
        username: '{{ cimc_username }}'
        password: '{{ cimc_password }}'
        validate_certs: false
        content: |
          <configConfMo><inConfig>
            <computeRackUnit dn="sys/rack-unit-1" adminPower="up"/>
          </inConfig></configConfMo>
      delegate_to: localhost
