---
- name: Power up Cisco blade servers
  hosts: '{{hosts_group_name}}'
  gather_facts: no

  tasks:
    - name: Power up server
      imc_rest:
        hostname: '{{ hostvars[inventory_hostname].ucs_ip }}'
        username: '{{ ucs_user }}'
        password: '{{ ucs_pass }}'
        validate_certs: false
        content: |
          <configConfMo cookie="1502884658/ca2c8e57-77eb-4e76-b3d1-3dca87fd0d1b" inHierarchical="false">
          <inConfig>
          <lsPower state="up" dn="{{ item }}/power" status="created,modified" ></lsPower>
          </inConfig>
          </configConfMo>
      loop: '{{ hostvars[inventory_hostname].blades }}'
      delegate_to: localhost
