---
- name: Power down SMC servers
  hosts: '{{hosts_group_name}}'
  gather_facts: no
  tasks:
    - name: Power down Supermicro server
      community.general.ipmi_power:
        user: 'ADMIN'
        password: '{{ smc_password }}'
        state: 'shutdown'
        name: '{{ inventory_hostname }}'
